# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - test
  - quality_gate
  # - build
  - deploy

variables:
  GIT_STRATEGY: fetch

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# Generic scripts
.poetry_setup: &poetry_setup
  before_script:
    - python -V
    - python -m pip install --upgrade pip
    - python -m pip install pipx
    - python -m pipx install poetry==1.6.1
    - export PATH=$PATH:$HOME/.local/bin

# Job Definitions
test_frontend:
  stage: test
  image: node:20
  script:
    - cd code/frontend
    - npm i
    - npm run coverage
  artifacts:
    paths:
      - 'code/frontend/coverage/lcov.info'
      - 'code/frontend/coverage/cobertura-coverage.xml'
    reports:
      coverage_report:
        coverage_format: cobertura
        path: 'code/frontend/coverage/cobertura-coverage.xml'

test_backend:
  stage: test
  image: python:3.11-bookworm
  <<: *poetry_setup
  script:
    - cd code/backend
    - poetry lock
    - poetry install
    - poetry run coverage run
    - poetry run coverage report
    - poetry run coverage xml
  artifacts:
    paths:
      - 'code/backend/.coverage'
      - 'code/backend/coverage.xml'
    reports:
      coverage_report:
        coverage_format: cobertura
        path: 'code/backend/coverage.xml'

sonarqube_check:
  stage: quality_gate
  image:
    name: sonarsource/sonar-scanner-cli:5.0
    entrypoint: ['']
  needs:
    - job: test_frontend
      artifacts: true
    - job: test_backend
      artifacts: true
  variables:
    SONAR_USER_HOME: '${CI_PROJECT_DIR}/.sonar' # Defines the location of the analysis task cache
    GIT_DEPTH: '0' # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: '${CI_JOB_NAME}'
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  allow_failure: true

# build_frontend:
#   stage: build
#   script:
#     - cd code/frontend
#     - npm install
#     - npm run build

deploy_to_production:
  stage: deploy
  script:
    - echo "Deploying!"
  only:
    - main
