version: "3.5"

services:
  backend:
    image: t1-check-mates/backend
    container_name: t1-check-mates-backend
    build:
      context: ../code/backend/
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - 8000:8000
    networks:
      - deploy
    restart: unless-stopped

  frontend:
    image: t1-check-mates/frontend
    container_name: t1-check-mates-frontend
    build:
      context: ../code/frontend/
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - 3000:5173
    networks:
      - deploy
    restart: unless-stopped

  bot:
    image: t1-check-mates/bot
    container_name: t1-check-mates-bot
    build:
      context: ../code/bot/
      dockerfile: Dockerfile
      no_cache: true
    environment:
      - "TELEGRAM_TOKEN=${TELEGRAM_TOKEN}"
      - "BACKEND_URL=${BACKEND_URL}"
    networks:
      - deploy
    restart: unless-stopped

networks:
  deploy:
