# NOTE: per qualche motivo prima che facessi daemon reload a mano, non funzionava
# si ha che la secret immessa nel codice è undefined, nonostante
- name: Configure webhook
  hosts: main
  vars_prompt:
    - name: GITLAB_WEBHOOK_SECRET
      prompt: Enter global password for gitlab webhook
      private: true
      confirm: true
  tasks:
    - name: install service
      become: yes
      ansible.builtin.template:
        src: files/gitlab_webhook.service.j2
        dest: /etc/systemd/system/gitlab_webhook.service
        owner: root
        group: root
        mode: 0755

    - name: start service
      become: yes
      ansible.builtin.service:
        name: gitlab_webhook
        state: started
        enabled: yes

    - name: restart service
      become: yes
      ansible.builtin.service:
        name: gitlab_webhook
        state: restarted
        enabled: yes

    - name: reload daemon
      become: yes
      ansible.builtin.systemd:
        daemon_reload: yes