version: "3.5"

x-environment:
  &default-back-environment
  POSTGRES_DB: "taiga"
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  POSTGRES_HOST: "taiga-db"
  TAIGA_SECRET_KEY: "${SECRET_KEY}"
  RABBITMQ_USER: "${RABBITMQ_USER}"
  RABBITMQ_PASS: "${RABBITMQ_PASS}"
  CELERY_ENABLED: "False"
  ENABLE_GITLAB_AUTH: "True"
  GITLAB_API_CLIENT_ID: "7508efabdf725c7e9b7f0dbe1b8e0641f6d2061dfcffb69d5281e45feddf71b0"
  GITLAB_API_CLIENT_SECRET: "gloas-52a254ebd1ac3b0f2e643ec107135341137cf8e075bd4949c40daacf343991a6"
  GITLAB_URL: "http://gitlab.t1-check-mates.mooo.com/"
  PUBLIC_REGISTER_ENABLED: "True"

x-volumes:
  &default-back-volumes
  - taiga-static-data:/taiga-back/static
  - taiga-media-data:/taiga-back/media
  # - ./config.py:/taiga-back/settings/config.py

services:
  taiga-manage:
    image: taigaio/taiga-back:latest
    environment: *default-back-environment
    depends_on:
      - taiga-db
    entrypoint: "python manage.py"
    volumes: *default-back-volumes
    networks:
      - taiga
